{% set name = "nclpy" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6185b01f90cc71364ee9bdb8718f0a46248c93bdfe94a1c28189cc36cce1cbd5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - earthengine-api
    - folium
    - ipyleaflet
    - pyshp
    - python >=3.6

test:
  imports:
    - nclpy

about:
  home: https://github.com/HJRubin/nclpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for working with NCL
  doc_url: https://hjrubin.github.io/nclpy/
  dev_url: https://github.com/HJRubin/nclpy

extra:
  recipe-maintainers:
    - HJRubin
